# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(480, 320)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resultLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLabel.setEnabled(False)
        self.resultLabel.setGeometry(QtCore.QRect(0, 200, 461, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(50, 240, 150, 31))
        self.captureButton.setObjectName("captureButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(270, 240, 150, 31))
        self.exitButton.setObjectName("exitButton")
        self.camWidget = QtWidgets.QLabel(self.centralwidget)
        self.camWidget.setGeometry(QtCore.QRect(0, 0, 480, 190))
        self.camWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.camWidget.setObjectName("camWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Two-Cell Contractions"))
        self.resultLabel.setText(_translate("MainWindow", "Label"))
        self.captureButton.setText(_translate("MainWindow", "Capture and Identify"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.camWidget.setText(_translate("MainWindow", "Feed"))
