# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/outputUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OutputDialog(object):
    def setupUi(self, OutputDialog):
        OutputDialog.setObjectName("OutputDialog")
        OutputDialog.resize(480, 320)
        self.closeButton = QtWidgets.QPushButton(OutputDialog)
        self.closeButton.setGeometry(QtCore.QRect(170, 230, 141, 41))
        self.closeButton.setObjectName("closeButton")
        self.outputLabel = QtWidgets.QLabel(OutputDialog)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 480, 201))
        self.outputLabel.setObjectName("outputLabel")

        self.retranslateUi(OutputDialog)
        QtCore.QMetaObject.connectSlotsByName(OutputDialog)

    def retranslateUi(self, OutputDialog):
        _translate = QtCore.QCoreApplication.translate
        OutputDialog.setWindowTitle(_translate("OutputDialog", "Captured Image"))
        self.closeButton.setText(_translate("OutputDialog", "Close"))
        self.outputLabel.setText(_translate("OutputDialog", "Output Here"))
